Add --verbose, move checks around

diff --git a/libexec/setzer/setzer-bot b/libexec/setzer/setzer-bot
--- a/libexec/setzer/setzer-bot
+++ b/libexec/setzer/setzer-bot
@@ -18,6 +18,10 @@ function log {
   echo "[$(date "+%D %T")] $*"
 }
 
+function verbose {
+  [[ $SETZER_VERBOSE ]] && log "[V] $*"
+}
+
 function getnode {
   # Check if connected to node
   export RPC_TIMEOUT=${RPC_TIMEOUT:-15s}
@@ -26,64 +30,64 @@ function getnode {
     log "Trying on rpc port $ETH_RPC_PORT."
     syncing=$(timeout $RPC_TIMEOUT seth rpc eth_syncing 2> /dev/null) \
   	  && peers=$(timeout $RPC_TIMEOUT seth rpc net_peerCount 2> /dev/null) \
-  	  && blockNumber=$(timeout $RPC_TIMEOUT seth block latest number 2> /dev/null || true) \
+      && timestamp=$(($(date +%s) - $(seth block latest timestamp 2>/dev/null || echo 0) > 60)) \
   	  && sanity=($(timeout $RPC_TIMEOUT setzer peek "$SETZER_FEED" 2> /dev/null || true))
-    [[ $syncing == "false" ]] && [[ $peers -gt 0 ]] && [[ $blockNumber -gt 0 ]] && [[ $sanity ]] \
+    [[ $syncing == "false" ]] && [[ $peers -gt 0 ]] && [[ $timestamp = 0 ]] && [[ $sanity ]] \
   	  && running_client=1  && break 
   done
   
   if [ "${running_client:-0}" -ne 1 ]; then
    log "Not connected to Ethereum, retry in 5 seconds..."
+   verbose "Syncing:   $syncing (should be false)"
+   verbose "Peers:     $peers (should be > 0)"
+   verbose "Timestamp: $timestamp (should be 0)"
+   verbose "Sanity:    $sanity (should be not empty)"
    sleep 5
    exec "$0" "$@"
   fi
   log "Node running on RPC port $ETH_RPC_PORT."
 }
+
+# Global configuration
+[[ -e /etc/setzer.conf ]] && . /etc/setzer.conf
+
+# Local configuration (via -C or --config)
+# Useful for running multiple bots on one box
+[[ -e $SETZER_CONF ]] && . $SETZER_CONF
+
+#get valid node
+getnode
+
+[[ $ETH_FROM ]] || errors+=("No default account set. Please set it via ETH_FROM ")
+[[ $SETZER_FEED ]] || errors+=("No price feed set. Please set it via SETZER_FEED ")
+[[ $SETZER_MEDIANIZER ]] || errors+=("No medianizer set. Please set it via SETZER_MEDIANIZER ")
+[[ $SETZER_SOURCES ]] || errors+=("No price sources set. Please set them via SETZER_SOURCES ")
+
+[[ $errors ]] && { printf '%s\n' "${errors[@]}"; exit 1; }
+
+[[ $SETZER_SPREAD ]] || export SETZER_SPREAD=1
+
+[[ $SETZER_INTERVAL_SECONDS ]] || export SETZER_INTERVAL_SECONDS=60
+[[ $SETZER_WAIT_FOR_RESEND ]] || export SETZER_WAIT_FOR_RESEND=120
+
+[[ $SETZER_AUTO ]] && echo AUTO mode ON
+
+# Gas stuff
+[[ $SETZER_INITIAL_GAS_PRICE ]] || export SETZER_INITIAL_GAS_PRICE=`setzer gas`
+[[ $SETZER_GAS_PRICE_INCREMENT ]] || export SETZER_GAS_PRICE_INCREMENT=`seth --to-wei 5 gwei`
+[[ $SETZER_MAX_GAS_PRICE ]] || export SETZER_MAX_GAS_PRICE=`seth --to-wei 350 gwei`
+
+# NOTE: Nice way to see if bots are updated. Increase this by 1 on new versions :)
+export ETH_GAS=200007
+
 # Initialization
 if ! [[ $SETZER_BOT_INIT ]]; then
   export SETZER_BOT_INIT=1
   export SETH_ASYNC=yes
 
-  # Global configuration
-  [[ -e /etc/setzer.conf ]] && . /etc/setzer.conf
-
-  # Local configuration (via -C or --config)
-  # Useful for running multiple bots on one box
-  [[ -e $SETZER_CONF ]] && . $SETZER_CONF
-
-  #get valid node
-  getnode
-
   echo "--------- STARTING SETZER BOT ---------"
   echo "Bot started `date`"
   
-  [[ $ETH_FROM ]] || errors+=("No default account set. Please set it via ETH_FROM ")
-  [[ $SETZER_FEED ]] || errors+=("No price feed set. Please set it via SETZER_FEED ")
-  [[ $SETZER_MEDIANIZER ]] || errors+=("No medianizer set. Please set it via SETZER_MEDIANIZER ")
-  [[ $SETZER_SOURCES ]] || errors+=("No price sources set. Please set them via SETZER_SOURCES ")
-  
-  [[ $errors ]] && { printf '%s\n' "${errors[@]}"; exit 1; }
-
-
-  [[ $SETZER_SPREAD ]] || export SETZER_SPREAD=1
-
-  [[ $SETZER_INTERVAL_SECONDS ]] || export SETZER_INTERVAL_SECONDS=60
-  [[ $SETZER_WAIT_FOR_RESEND ]] || export SETZER_WAIT_FOR_RESEND=120
-
-  [[ $SETZER_AUTO ]] && echo AUTO mode ON
-
-  # Gas stuff
-  [[ $SETZER_INITIAL_GAS_PRICE ]] || export SETZER_INITIAL_GAS_PRICE=`setzer gas`
-  [[ $SETZER_GAS_PRICE_INCREMENT ]] || export SETZER_GAS_PRICE_INCREMENT=`seth --to-wei 5 gwei`
-  [[ $SETZER_MAX_GAS_PRICE ]] || export SETZER_MAX_GAS_PRICE=`seth --to-wei 350 gwei`
-  
-  # TODO: these should be automatic
-  export ETH_GAS_PRICE=$SETZER_INITIAL_GAS_PRICE
-
-  # NOTE: Nice way to see if bots are updated. Increase this by 1 on new versions :)
-  export ETH_GAS=200007
-
-
   echo "Default account:     $ETH_FROM"
   echo "Feed address:        $SETZER_FEED"
   echo "Medianizer address:  $SETZER_MEDIANIZER"
@@ -96,10 +100,12 @@ if ! [[ $SETZER_BOT_INIT ]]; then
   echo ""
   echo "Price check loop:    $SETZER_INTERVAL_SECONDS seconds"
   echo "Resend tx loop  :    $SETZER_WAIT_FOR_RESEND seconds"
+  echo ""
   echo "------- INITIALIZATION COMPLETE -------"
 fi
 
 getnode
+
 expires=$(setzer expires "$SETZER_FEED")
 log "Expires in `setzer --format "$expires"`"
 if [ "$expires" -lt 3600 ]; then
@@ -113,7 +119,7 @@ new=$(setzer average $SETZER_SOURCES)
 spread=$(setzer spread "$old" "$new")
 log "Old ($old) New ($new) Spread ($spread)"
 test=$(bc <<< "${spread#-} >= ${SETZER_SPREAD}")
-
+# Check if value has changed more than $SPREAD %
 if [[ ${test} -ne 0 ]]; then
   needsupdate="yes"
   log "Spread larger than $SETZER_SPREAD, will update."
@@ -153,15 +159,24 @@ if [[ $needsupdate ]]; then
   [[ ! $SETZER_AUTO ]] && read -r -p "Send transaction? [y/N] " response
   if [[ $SETZER_AUTO || "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
     CURRENT_LOOP=1
-    # TODO: check if $PENDING_TRANSACTION_NONCE
-    nonce=$(seth nonce "$ETH_FROM")
-    export ETH_NONCE=$nonce
+    # If there is no pending tx, reset initial gas price and nonce
+    # TODO: let user choose if setzer will handle starting gas
+    if ! [[ $ptn ]]; then
+      reset_gas=`setzer gas`
+      [[ $reset_gas ]] || reset_gas=`seth gas-price`
+      export ETH_GAS_PRICE=$reset_gas
+      nonce=$(seth nonce "$ETH_FROM")
+      export ETH_NONCE=$nonce
+    fi
     until=$(date +%s -d'+6 hour')
     log "Sending with nonce $ETH_NONCE and gas price $ETH_GAS_PRICE wei"
     tx=$(setzer post "$SETZER_FEED" "$new" "$until" "$SETZER_MEDIANIZER")
     if [[ $tx ]]; then
       log $tx
       export PENDING_TRANSACTION_NONCE=$nonce
+    else
+      # No transaction created. Either nonce issues or needs higher gas price
+      log "Error creating transaction..."
     fi
   fi
 fi
