testing

diff --git a/libexec/setzer/setzer-bot b/libexec/setzer/setzer-bot
--- a/libexec/setzer/setzer-bot
+++ b/libexec/setzer/setzer-bot
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
-### setzer-bot -- omg
-### ermagherd
+### setzer-bot -- really cool bot
+### Usage: setzer bot [--interactive]
+###
+### Instructions very soon
 #set -e
 
 # Initialization
@@ -10,18 +12,19 @@ if ! [[ $SETZER_BOT_INIT ]]; then
   export SETH_ASYNC=yes
   echo "--------- STARTING SETZER BOT ---------"
   echo "Bot started `date`"
+  
   [[ $ETH_FROM ]] || errors+=("No default account set. Please set it via ETH_FROM ")
   [[ $SETZER_FEED ]] || errors+=("No price feed set. Please set it via SETZER_FEED ")
   [[ $SETZER_MEDIANIZER ]] || errors+=("No medianizer set. Please set it via SETZER_MEDIANIZER ")
   [[ $SETZER_SOURCES ]] || errors+=("No price sources set. Please set them via SETZER_SOURCES ")
+  
+  [[ $errors ]] && { printf '%s\n' "${errors[@]}"; exit 1; }
 
   [[ $SETZER_LOOP_SECONDS ]] || export SETZER_LOOP_SECONDS=60
 
   [[ $SETZER_LOOPS_BETWEEN_PRICE_INCREASE ]] || export SETZER_LOOPS_BETWEEN_PRICE_INCREASE=4
 
-  [[ $errors ]] && { printf '%s\n' "${errors[@]}"; exit 1; }
-
-  [[ $1 = --interactive ]] && SETZER_INTERACTIVE=yes
+  [[ $SETZER_INTERACTIVE || $1 = --interactive ]] && { SETZER_INTERACTIVE=yes; echo Interactive mode ON; }
   
   export ETH_GAS_PRICE=`seth --to-wei 1 gwei`
   export ETH_GAS=200000
@@ -33,8 +36,11 @@ if ! [[ $SETZER_BOT_INIT ]]; then
   echo "Starting gas price: $ETH_GAS_PRICE wei"
 fi
 
-[[ $SETZER_TEST ]] && echo test is set
-exit;
+# Check if connected to node
+# TODO: use something other than gas price
+chain=$(seth gas-price 2> /dev/null)
+[[ $chain ]] || { echo No connection, will try in 10 seconds; sleep 10; exec "$0" "$@"; }
+
 # Check if we have transactions pending
 txs=($PENDING_TRANSACTIONS)
 if [[ ${#txs[@]} -gt 0 ]]; then
@@ -70,7 +76,7 @@ fi
 
 SPREAD=1.5
 gas=$(seth gas-price)
-echo "Current gas price is $gas wei"
+echo "Current gas price:  $gas wei"
 [[ $gas -gt 21000000000 ]] && echo "WARNING: Higher than normal gas price"
 
 
