Shellhcheck fixes

diff --git a/libexec/setzer/setzer-bot b/libexec/setzer/setzer-bot
--- a/libexec/setzer/setzer-bot
+++ b/libexec/setzer/setzer-bot
@@ -30,31 +30,32 @@ function verbose {
 function getnode {
   # Check if connected to node
   export RPC_TIMEOUT=${RPC_TIMEOUT:-15s}
-  peers="$(timeout "$RPC_TIMEOUT" seth rpc net_peerCount 2> /dev/null || echo 0)" \
-  && timestamp="$(( $(date +%s) - $(timeout "$RPC_TIMEOUT" seth block latest timestamp 2>/dev/null || echo 0) ))"
-  [[ $peers -gt 0 ]] && [[ $timestamp -lt 90 ]] && running_client=1
+  while [ "${running_client:-0}" -ne 1 ]; do
+    peers="$(timeout "$RPC_TIMEOUT" seth rpc net_peerCount 2> /dev/null || echo 0)" \
+    && timestamp="$(( $(date +%s) - $(timeout "$RPC_TIMEOUT" seth block latest timestamp 2>/dev/null || echo 0) ))"
+    [[ $peers -gt 0 ]] && [[ $timestamp -lt 90 ]] && running_client=1
   
-  if [ "${running_client:-0}" -ne 1 ]; then
-   log "Not connected to Ethereum, retry in 5 seconds..."
-   verbose "Peers:      $peers (should be > 0)"
-   verbose "Last block: $timestamp (should be < 90)"
-   sleep 5
-   exec "$0" "$@"
-  fi
+    log "Not connected to Ethereum, retry in 5 seconds..."
+    verbose "Peers:      $peers (should be > 0)"
+    verbose "Last block: $timestamp (should be < 90)"
+    sleep 5
+  done
 }
 
 export PATH="$PATH:/usr/local/bin/:/usr/bin/"
 
 # Global configuration
 if [[ -e /etc/setzer.conf ]]; then
-  . /etc/setzer.conf
+  # shellcheck source=/etc/setzer.conf
+  . "/etc/setzer.conf"
   #verbose "Imported configuration from /etc/setzer.conf"
 fi
 
 # Local configuration (via -C or --config)
 # Useful for running multiple bots on one box
 if [[ -e $SETZER_CONF ]]; then
-  . $SETZER_CONF
+  # shellcheck source=/etc/setzer.conf
+  . "$SETZER_CONF"
   #verbose "Imported configuration from $SETZER_CONF"
 fi
 
@@ -66,7 +67,7 @@ getnode
 [[ $SETZER_MEDIANIZER ]] || errors+=("No medianizer set. Please set it via SETZER_MEDIANIZER ")
 #[[ $SETZER_SOURCES ]] || errors+=("No price sources set. Please set them via SETZER_SOURCES ")
 
-[[ $errors ]] && { printf '%s\n' "${errors[@]}"; exit 1; }
+[[ ${errors[*]} ]] && { printf '%s\n' "${errors[@]}"; exit 1; }
 
 [[ $SETZER_SPREAD ]] || export SETZER_SPREAD=2
 
@@ -75,7 +76,8 @@ getnode
 
 [[ $SETZER_AUTO ]] && log "AUTO mode ON"
 
-[[ $SETZER_MAX_GAS_PRICE ]] || export SETZER_MAX_GAS_PRICE=`seth --to-wei 350 gwei`
+max_gas=$(seth --to-wei 350 gwei)
+[[ $SETZER_MAX_GAS_PRICE ]] || export max_gas
 
 # NOTE: Nice way to see if bots are updated. Increase this by 1 on new versions :)
 export ETH_GAS=200014
@@ -86,7 +88,7 @@ if ! [[ $SETZER_BOT_INIT ]]; then
   export SETH_ASYNC=yes
 
   echo "--------- STARTING SETZER BOT ---------"
-  echo "Bot started `date`"
+  echo "Bot started $(date)"
   
   echo "Default account:     $ETH_FROM"
   echo "Feed address:        $SETZER_FEED"
@@ -103,14 +105,14 @@ if ! [[ $SETZER_BOT_INIT ]]; then
 fi
 
 expires=$(setzer expires "$SETZER_FEED")
-log "Expires in `setzer --format "$expires"`"
+log "Expires in $(setzer --format "$expires")"
 if [ "$expires" -lt 3600 ]; then
   log "Expires in less than an hour, will update."
   needsupdate="yes"
 fi
 
-old=($(setzer peek "$SETZER_FEED"))
-old=${old[0]}
+feed=($(setzer peek "$SETZER_FEED"))
+old=${feed[0]}
 
 if [[ $SETZER_SOURCES == *"mkr" ]]; then
   new=$(setzer price mkr || echo 0)
@@ -139,7 +141,7 @@ fi
 # Check if we have transactions pending
 ptn=$PENDING_TRANSACTION_NONCE
 if [[ $ptn ]]; then
-  nonce=$(seth nonce $ETH_FROM)
+  nonce=$(seth nonce "$ETH_FROM")
   verbose "Transaction pending. Checking if nonce $nonce has increased."
   if [[ "$nonce" -gt "$ptn"  ]]; then
     mined="yes"
@@ -153,7 +155,8 @@ if [[ $mined ]]; then
   export PENDING_TRANSACTION_NONCE=
 else
   if [[ $ptn ]]; then
-    export CURRENT_LOOP=$(($CURRENT_LOOP + 1))
+    loop=$(( CURRENT_LOOP + 1 ))
+    export CURRENT_LOOP=$loop
     # increase gas price by 15%
     # should be 10% but I can never get it to work...
     verbose "Increasing gas price by 15%"
@@ -176,7 +179,8 @@ if [[ $needsupdate ]]; then
     # If there is no pending tx, reset initial gas price and nonce
     # TODO: let user choose if setzer will handle starting gas
     if ! [[ $ptn ]]; then
-      export ETH_NONCE=$(seth nonce "$ETH_FROM")
+      nonce=$(seth nonce "$ETH_FROM")
+      export ETH_NONCE=nonce
       reset_gas=$(setzer gas safe)
       [[ $reset_gas ]] || reset_gas=$(seth gas-price)
       export ETH_GAS_PRICE=$reset_gas
